name: Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
      - name: Install
        run: npm ci
      - name: ESLint
        run: |
          npm run lint
          npm run format
